name: Weekly - Download NVD CVE & CPE

on:
  schedule:
    - cron: '30 21 * * 0'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-nvd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Creating output directory
        run: mkdir -p output

      - name: Download recent NVD CVE
        run: |
          curl -L -o output/nvdcve-2.0-recent.json.gz "https://nvd.nist.gov/feeds/json/cve/2.0/nvdcve-2.0-recent.json.gz"
          curl -L -o output/nvdcve-2.0-modified.json.gz "https://nvd.nist.gov/feeds/json/cve/2.0/nvdcve-2.0-modified.json.gz"
          gunzip -f output/nvdcve-2.0-recent.json.gz
          gunzip -f output/nvdcve-2.0-modified.json.gz

      - name: Download all NVD CVE
        run: |
          for year in $(seq 2002 $(date +%Y))
          do
            curl -o "output/nvdcve-2.0-${year}.json.gz" "https://nvd.nist.gov/feeds/json/cve/2.0/nvdcve-2.0-${year}.json.gz"
          done

      - name: Download NVD CPE 2.0 bundle
        run: |
          echo "Downloading NVD CPE 2.0 JSON Bundle..."
          curl -f -L -o cpe_bundle.tar.gz "https://nvd.nist.gov/feeds/json/cpe/2.0/nvdcpe-2.0.tar.gz"

      - name: Extract and Merge JSON Chunks
        run: |
          tar -xzvf cpe_bundle.tar.gz
          
          python3 - <<EOF
          import json
          import os
          import gzip
          import glob
          chunk_files = sorted(glob.glob('nvdcpe-2.0-chunks/*.json'))
          master_list = []
          print(f"Merging {len(chunk_files)} chunks...")
          for file in chunk_files:
              with open(file, 'r', encoding='utf-8') as f:
                  data = json.load(f)
                  # Le NIST place les items dans la clé 'products'
                  if 'products' in data:
                      master_list.extend(data['products'])
              print(f"Loaded {file}")
          output_path = 'output/nvd_cpe_master_2.0.json.gz'
          with gzip.open(output_path, 'wt', encoding='utf-8') as f:
              json.dump({"products": master_list}, f)
          print(f"✅ Master file created with {len(master_list)} items.")
          EOF

      - name: Clean up NVD cpe chunks and archive
        run: rm -rf nvdcpe-2.0-chunks cpe_bundle.tar.gz

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'          
          git add .      
          if git diff --staged --quiet; then
            echo "No change"
          else
            git commit -m "chore: update refsets $(date +'%Y-%m-%d')"
            git push
          fi